### ISSUE TITLE
Web application structure

### ISSUE THREAD

**Issue by cybersiddhu** [dictyBase/gh-issue#1]
It expected to have the following folders

* middlewares : For middlewares specific to this application.
  * Use [logging](https://godoc.org/github.com/dictyBase/go-middlewares/middlewares/logrus) middleware. Look [here](https://github.com/dictyBase/modware/blob/master/commands/server/server.go) for how to chain the middleware.
   
* resources: The web request handlers.
  * Use [error helper](https://godoc.org/github.com/dictyBase/apihelpers/apherror) package if necessary.

* commands: To run and manage the server.
    * validate:  The validate the command parameters.
* routes: All the path/routes.

The `main.go` file will be the entrypoint.

**Comment by cybersiddhu** [comment]
The issue will have the following [structure](https://github.com/dictyBase/Migration/issues/86)

**Comment by rlaher** [comment]
Current status: Working on implementing markdown. It's complicated because the JSON structs are so long/there's so many of them. I thought about using string substitution but that seems unwieldy.  I'm thinking of creating header/row structs for the tables that will need to be created, and creating a ToMarkdown function that takes JSON structs as input and outputs a markdown text string.

**Comment by rlaher** [comment]
**Status Update**
-Created model.go file which contains the new OrderInfo struct, the necessary methods for the jsonapi parsing, and the function Jsondecoder which parses JSON data into an OrderInfo struct. Have not yet implemented the relationships.
-Started implementing cli in the main.go file. Able to get the application running, but unable to run my TestFunction command from commands.go. The error I get is "ERROR invalid Action type. Must be `func(*Context`)` or `func(*Context) error)."
-handlers.go can be ignored (for now). The IssueParser function will likely be useful in the future.
**Plan:**
-I figured the next step would be to get an application running that takes the OrderInfo JSON (with no relationships yet) and submits an issue to the github
**Questions:**
-How to authenticate github? Do I store my username and password in the code or should it be passed as a paramater in the JSON? 
-Unsure why I can't get TestFunction command to work
-What other commands will be necessary?
-How to implement routing? Should it go in routes.go or should I implement it in the RunServer function like in the modware example you showed me?
