### ISSUE TITLE
Middleware for check POST request

### ISSUE THREAD

**Issue by cybersiddhu** [dictyBase/gh-issue#7]
Write a middleware which check for the presence of expected `POST` body. In short, it is expected to check for 
* If a `POST` body is given
* If the posted json have the correct structure
* If it fails return a proper HTTP error response
* Currently it is not a reusable/library package, should only be used for this application. So, it is expected to reside in `middleware` folder.

**Comment by rlaher** [comment]
JsonDecoder function located in handlers.go now takes care of validating the post request as well as returns the struct Orderinfo struct which holds the decoded data.

**Comment by cybersiddhu** [comment]
It's not a middleware, write a middleware first
